### PR TITLE
Fix: Retrieve translated properties in search queries

### PR DESCRIPTION
**Pull request by polishq**
#### What problem is this solving?

If translations for a text-based product specification have been registered, currently they are successfully retrieved by the `product` and `productsByIdentifier` queries, but not by `products` or `productSearch`. 

The most obvious cause for this was that in the `properties` field resolver, there was a conditional causing the translation logic to be skipped if `product.origin` was "intelligent-search", which was true for the `products` and `productSearch` queries.

Digging deeper, when this conditional was true it also meant that `product.allSpecifications`, which was necessary for the translation logic to run, was `undefined`. However, in this scenario the list of specification fields is available in a different place: `product.properties`. 

This PR adjusts the logic so that translations can be retrieved consistently in all four queries listed above.

#### How should this be manually tested?

New version linked here: https://arthur--beautycounterqa.myvtex.com

Use this cURL for testing:

```
curl --location 'https://arthur--beautycounterqa.myvtex.com/_v/private/graphql/v1?locale=fr-CA&__bindingAddress=qa.beautycountertest.com%2Ffr-ca' \
--header 'VtexIdclientAutCookie: eyJhb...' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query {\r\n    productSearch(fullText: \"1006\") @context(provider: \"vtex.search-graphql\") {\r\n        products {\r\n        productName\r\n        description\r\n        properties {\r\n            originalName\r\n            name\r\n            values\r\n        }\r\n        skuSpecifications {\r\n            field {\r\n                originalName\r\n                name\r\n            }\r\n            values {\r\n                originalName\r\n                name\r\n            }\r\n        }\r\n    }}\r\n}","variables":{}}'
```

Look for the `shortDescription` field in the `properties`. With the linked version, it is correctly returned in French. Repeat the test against the master workspace and you will see that it is returned in English. 

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Comment by polishq** [comment]
Here's a cURL against master (current stable version) showing that the `properties` are already successfully translated in the `product` query:

```
curl --location 'https://beautycounterqa.myvtex.com/_v/private/graphql/v1?locale=fr-CA&__bindingAddress=qa.beautycountertest.com%2Ffr-ca' \
--header 'VtexIdclientAutCookie: eyJhb...' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query {\r\n    product(identifier: { field: id, value: 1006}) @context(provider: \"vtex.search-graphql\") {\r\n        productName\r\n        description\r\n        properties {\r\n            originalName\r\n            name\r\n            values\r\n        }\r\n        skuSpecifications {\r\n            field {\r\n                originalName\r\n                name\r\n            }\r\n            values {\r\n                originalName\r\n                name\r\n            }\r\n        }\r\n    }\r\n}","variables":{}}'
```

Again, check the `shortDescription` and note that it is correctly returned in French.

**Comment by thalytafabrine** [comment]
hey @polishq, how are you? 😄 
actually I think this PR is unnecessary because the `properties` field should already come with the values translated into the language selected in the search, this is the reason why we don't get translations in search-resolver when the origin is`intelligent-search`...
it looks like this scenario you brought up is a bug in the translations of this store in indexing, is it ok with you if I investigate this with my team before reviewing the PR?

**Comment by polishq** [comment]
> hey @polishq, how are you? 😄 actually I think this PR is unnecessary because the `properties` field should already come with the values translated into the language selected in the search, this is the reason why we don't get translations in search-resolver when the origin is`intelligent-search`... it looks like this scenario you brought up is a bug in the translations of this store in indexing, is it ok with you if I investigate this with my team before reviewing the PR?

@thalytafabrine Sure, do you have an estimate of when this investigation can happen? If the timeline gets tight, can we merge this PR as a temporary fix while the team works on the underlying bug?

**Comment by garrucho** [comment]
For the record, @thalytafabrine is right, and the Catalog/Indexer team and its Experts are aware of indexing issues. It's very important to understand with them how this will be taken at the indexing level.

**Review by thalytafabrine — APPROVED** [review]
hey @polishq! we discovered that this is a KI that is a little complex to solve, and that it has been around for a while.. :sadge:
given that, I am approving your PR and we can continue with this workaround until we have a definitive solution. thanks for your patience!

**Pull request merged**
